In [2]:
# Import necessary libraries
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

%load_ext autoreload
%autoreload 2

# Load test module for sanity check
from test_utils import test

Data Generation
===

In [3]:
num_samples, num_features = 10, 5

In [4]:
np.random.seed(10)
data = np.random.rand(num_samples, num_features)

Solution
===

In [5]:
print(data)

[[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
 [0.22479665 0.19806286 0.76053071 0.16911084 0.08833981]
 [0.68535982 0.95339335 0.00394827 0.51219226 0.81262096]
 [0.61252607 0.72175532 0.29187607 0.91777412 0.71457578]
 [0.54254437 0.14217005 0.37334076 0.67413362 0.44183317]
 [0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]
 [0.8052232  0.52164715 0.90864888 0.31923609 0.09045935]
 [0.30070006 0.11398436 0.82868133 0.04689632 0.62628715]
 [0.54758616 0.819287   0.19894754 0.8568503  0.35165264]
 [0.75464769 0.29596171 0.88393648 0.32551164 0.1650159 ]]


In [ ]:
def standardize(x):
    """Stadartize the input data x

    Args:
        x: numpy array of shape=(num_samples, num_features)

    Returns:
        standartized data, shape=(num_samples, num_features)

    >>> standardize(np.array([[1, 2], [3, 4], [5, 6]]))
    array([[-1.22474487, -1.22474487],
           [ 0.        ,  0.        ],
           [ 1.22474487,  1.22474487]])
    """
    # ***************************************************
    # INSERT YOUR CODE HERE
    # TODO: standartize input data x
    # ***************************************************
    # Compute the mean and standard deviation for each dimension
    S, F = x.shape
    normalized_x = np.zeros((S, F))

    for f in range(F):
        print(x[:, f])
        mean = np.mean(x[:, f])
        std = np.std(x[:, f])
        normalized_x[:, f] = (x[:, f] - mean) / std
        print(normalized_x[:, f])
    return x


test(standardize)

❌ The are some issues with your implementation of `standardize`:
**********************************************************************
File "__main__", line 10, in standardize
Failed example:
    standardize(np.array([[1, 2], [3, 4], [5, 6]]))
Expected:
    array([[-1.22474487, -1.22474487],
           [ 0.        ,  0.        ],
           [ 1.22474487,  1.22474487]])
Got:
    [1 3 5]
    3.0 1.632993161855452
    [2 4 6]
    4.0 1.632993161855452
    array([[-1, -1],
           [ 0,  0],
           [ 1,  1]])
**********************************************************************


In [7]:
std_data = standardize(data)
print(std_data, "\n\n", np.mean(std_data, axis=0), "\n\n", np.std(std_data, axis=0))

NotImplementedError: 